title : bac0id's Blog
lang : zh-CN

#baseurl: "/Blog"
#url: "https://bac0id.github.io"
#permalink: /:categories/:year-:month/:title
#permalink: /:year/:month/:day/:title
permalink : /:year-:month-:day/:title
#permalink: /Blog

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
#excerpt_separator: <!--more-->
incremental         : false


timezone : Asia/Shanghai
copyright : bac0id 2020-2022
github_username : bac0id
github :
  is_project_page : true
  owner_name : bac0id
  owner_url : https://github.com/bac0id/
  show_forkme : false
theme : jekyll-theme-slate

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
